# Generated by Django 5.2.4 on 2025-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
                ('departure_time', models.CharField(max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
